{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "local-csi-driver.serviceAccountName" . }}
  namespace: {{ include "local-csi-driver.namespace" . }}
  labels: {{ include "local-csi-driver.labels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
imagePullSecrets:
{{- with .Values.imagePullSecrets }}
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end -}}